import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My First Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <ul className="flex gap-2 p-4">
            <li><Link href="/">Home</Link></li>
            <li><Link href="/blogs">Blogs</Link></li>
          </ul>
        </nav>
        <div>{children}</div>
      </body>
    </html>
  );
}
