import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My First Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <div className="flex justify-between items-center p-3">
            <h1 className="text-violet-700 font-semibold">{metadata.title}</h1>
            <ul className="flex gap-4 font-medium p-4 text-stone-800">
              <li>
                <Link href="/">Home</Link>
              </li>
              <li>
                <Link href="/blogs">Blogs</Link>
              </li>
            </ul>
          </div>
        </nav>
        <div>{children}</div>
      </body>
    </html>
  );
}
